# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: (Production) Build and deploy API 

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_LEROYNET }}
  
    # before running docker build && push, we run a custom pipeline to get our App Settings into the react applicaiton on build
    # - name: Extract App Settings
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.30.0
    #     inlineScript: |
    #       az --version
    #       az account set --subscription "SDM Production"
    #       chmod +x $GITHUB_WORKSPACE/scripts/az_to_env.py
    #       echo "-----> Copying settings to .env file."
    #       az webapp config appsettings list --name testapp --resource-group sdm --subscription "SDM Production" | $GITHUB_WORKSPACE/scripts/az_to_env.py > $GITHUB_WORKSPACE/client/.env

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://testappvariables-agdsggevh7fnbacp.azurecr.io
        username: github-push
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: testappvariables-agdsggevh7fnbacp.azurecr.io/testapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_LEROYNET }}
    
    - name: Deploy to Azure App Service
      uses: azure/CLI@v1
      with:
        inlineScript: |
              az webapp config container set \
              --name TestWebAppVar \  
              --resource-group TestAppVariables \
              --container-image-name testappvariables-agdsggevh7fnbacp.azurecr.io/testapp:${{ github.sha }}